### ISSUE TITLE
Algunas preguntas necesitan refinarse

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#32]
Qué es seguridad?
- Creo que esta pregunta como está planteada es irrelevante para el aprendizaje de la seguridad informática. En mi opinión sobra.

"¿Cuál de estos es un activo de información?"
"Puerta del Centro de Cómputo", demasiado obvia, qué tal "Los servidores de aplicaciones"

"Un empleado descontento constituye para la organización"
Creo que es demasiado ambigua y discutible.. qué tal  "Un empleado con rencor hacia la organización constituye para ella:",

"Seguridad de la información abarca",
Tiene opciones que están incluídas en otras opciones. Funcionaría mejor si es multirespuesta.

"Impactos que puede causar un ataque informático en una entidad",
 "Salud" es gramaticalmente incorrecto, qué tal "Sanitario" o "Laboral"

"¿Cuáles son las técnicas de influencia y manipulación utilizadas por los adversarios?",
 "Todas las anteriores": opción relacionada a otras

 "Las políticas de seguridad de información son:",
 "Los documentos que nadie conoce": demasiado obvia

**Comment by 4sseginfo** [comment]
[Preguntas Ciberalbum.xlsx](https://github.com/edwin-navarrete/cybersec_album/files/14216429/Preguntas.Ciberalbum.xlsx)

Las resaltadas son las respuestas correctas.

**Comment by edwin-navarrete** [comment]
Done
