### ISSUE TITLE
Mejoras de presentación de la tabla de clasificación

### ISSUE THREAD

**Issue by KaremVPintoF** [edwin-navarrete/cybersec_album#39]
La tabla de clasificación necesita:

1. Números con símbolo de porcentaje en la columna porcentaje de errores. Los valores en la fuente de datos van a venir como un valor entre cero y uno y en la UI deben aparecer como un valor entre cero y cien con símbolo de porcentaje %.
2. La columna de fecha debe incluir la hora y debe llamarse "Fecha y hora de inicio"
3. El tiempo total de respuesta debe mejor llamarse ("El tiempo total de respuesta (Segundos)"
4. La columna AlbumId debe llamarse simplemente "Álbum"
5. El orden de las columnas debe ser: Posición, AlbumId,  Fecha de inicio, Album finalizado, Preguntas Respondidas, Numero de errores y Porcentaje de errores, y tiempo total de respuesta.

**Comment by KaremVPintoF** [comment]
Falta saber en qué posición iría la columna "Tiempo total de respuesta"

**Comment by edwin-navarrete** [comment]
es la última columna @KaremVPintoF

**Comment by KaremVPintoF** [comment]
Listo, ya he revisado todo y creo que está correcto.

**Comment by edwin-navarrete** [comment]
No has hecho pull request, no se ha hecho merge de tu código en main. No lo cierres hasta que el código no esté en Main
