### ISSUE TITLE
El menú de UI Stat debe permitir navegar entre Tabla de Clasificación y otra vista vacía

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#43]
La tabla actual debe llamarse Tabla de Clasificación y es la vista por defecto. Sin embargo con el menú que se puede ver en la esquina superior izquierda debe incluir la Tabla de Clasificación y otra vista que por lo pronto llamaremos Monitor de Preguntas y que navega a una página con el mismo título y pro lo pronto completamente vacía.

**Comment by jcalderonagudelo** [comment]
Acabo de realizar push a partir de este issue, la asignación que había en el trello estaba a mi nombre y hasta ahora noto que está asignado a @KaremVPintoF. Espero no sea problema.

**Comment by edwin-navarrete** [comment]
@jcalderonagudelo Por fa actualiza con master porque hubieron un par de cambios en el lado el servidor

**Comment by jcalderonagudelo** [comment]
@edwin-navarrete No me deja actualizarla con master, me arroja el siguiente error en github desktop: 

![image](https://user-images.githubusercontent.com/85127168/236297419-a78d97cf-2740-412e-b24d-bf79959d53e9.png)

**Comment by edwin-navarrete** [comment]
Correcto, no está permitido hacer merge al Main. Lo que había pedido era que hiciera un rebase de su rama de desarrollo (actualizar su rama de desarrollo con lo nuevo en el Main), no que hicera merge de su rama al Main. Si ya terminó los cambios por fa cree el PR.

**Comment by jcalderonagudelo** [comment]
Entendido, lo acabo de realizar. Gracias @edwin-navarrete
