### ISSUE TITLE
Los datos presentados en la Tabla de Clasificación debe usar el servicio 

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#44]
La tabla debe usar los datos obtenidos a través del entrypoint del statServer descrito en:

[statServer debe tener URI /ranking](https://github.com/edwin-navarrete/cybersec_album/issues/42)

Cuando se cambia la selección de la fecha debe hacer una nueva petición de los datos.

Usar la siguiente consulta:
```
SELECT a.album_id,
a.started_on,
FROM_UNIXTIME(a.started_on / 1000),
a.ended_on is not null finalizacion_album,
COUNT(DISTINCT question_id) preguntas_respondidas,
COUNT(DISTINCT question_id) - SUM(success) numero_de_errores,
1 - SUM(success)/COUNT(DISTINCT question_id) porcentaje_error,
SUM(latency)/1000 AS tiempo_total_de_respuesta
FROM vw_user_answer ua
JOIN album a ON ua.album_id = a.album_id
WHERE DATE(FROM_UNIXTIME(a.started_on/1000)) = '2022-11-26' 
GROUP BY started_on, album_id
ORDER BY finalizacion_album DESC, tiempo_total_de_respuesta, SUM(success)/COUNT(DISTINCT question_id) DESC;
```

**Comment by jcalderonagudelo** [comment]
Ahora la tabla usa el servicio http://localhost:8001/ranking en vez de http://localhost:8001/user, se usó la consulta anterior tal y como se describe, excepto por la linea **WHERE DATE(FROM_UNIXTIME(a.started_on/1000)) = '2022-11-26' ** ya que lo que hice fue quitarla para que trajera todos los datos y añadí una columna de nombre posición que sería como el ranking **provisional** además aún sigue con el ordenamiento por frontend ya que no me dió el tiempo para poder implementarlo.
