### ISSUE TITLE
El orden de la tabla de clasificación es errado

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#47]
No está ordenado por los criterios previamente establecidos:
- Primero los que terminaron el álbum (Primero lo de sí y luego los de No)
- Luego por el porcentaje de error ascendente
- Finalmente por el tiempo de respuesta ascendente

El código ordena por tiempo de respuesta y luego ordena de nuevo por album terminado y luego número de errores (que es diferente al porcentaje).

**Comment by KaremVPintoF** [comment]
El ordenamiento fue revisado y en el código se hace primero el orden por tiempo, luego numero de errores y finalmente estado del album, para que se reordene adecuadamente según descarte, con lo cual la priorización queda: estado de album, número de errores y tiempo. Se descartó el hook y se creó el método sortArray con el fin de mantener el código simple.

Como porcentaje de error es equivalente a número de errores, al ser un campo calculado por medio de los errores, se había determinado que su uso era indiferente; sin embargo, se ha cambiado el ordenamiento para tomar porcentaje de error, teniendo en cuenta que es la proporción de errores respecto a las preguntas respondidas por el usuario.

Anotaciones:
-> Se retira el uso del cálculo *100 en el campo del front "porcentaje de error", debido a que se encuentra solucionado el formateo desde la sentencia SQL propia del proyecto de backend.

**Comment by edwin-navarrete** [comment]
@KaremVPintoF Aunque el front end puede ahorrar el trabajo de multiplicar por 100 el porcentaje de error, es una mala práctica representar porcentajes con números del cero al cien, muy similar a que un protocolo represente un booleano con "sí" y "no". Es el front end al que se le delega la mejor representación de la información, no al backend. Por esa razón por favor garantiza que el protocolo retorna valores entre cero y uno para el porcentaje, como está en el Main.

Por otro lado porcentaje de error _no_ es equivalente a número de errores. Te pongo el contra ejemplo: Alguien responde con dos errores a 10 de las 14 preguntas. Otro se equivoca en dos preguntas pero respondió 14. Según tu criterio los dos serían iguales, pero en realidad el segundo es mejor.

**Comment by KaremVPintoF** [comment]
Si en el main que señala mira la instrucción en el backEnd de donde salen los datos del porcentaje, verá que se hace una instrucción en la que se divide por cien el número obtenido, es de ahí que sale un porcentaje decimal. Al final el número debe quedar entero, por eso se quita la parte que divide el número en 100, porque tendría que añadirse en el front de nuevo una multiplicación por 100 y estaría siendo redundante, a eso me refiero y por eso lo dejé así.

En cuanto a lo otro, arriba claramente explico que en un inicio, en las reuniones dijimos que era equivalente, pero como puede ver explico que finalmente son distintos porque uno es el número de errores total que tuvo la persona y el otro es un porcentaje respecto a las preguntas respondidas, que por sí mismo da una explicación más detallada del progreso del usuario. Todo esto para dar justificación al cambio.

**Comment by KaremVPintoF** [comment]
Igualmente, todos estos cambios que le platico también se ven reflejados en la branch 49, si quiere revisarla, le agradecería si pudiera cerrar este pull request y ahora mirar el otro. Aquí finalmente lo que hice fue explicar el funcionamiento del método sortArray, dividiéndolo y expandiéndolo para hacerlo más sencillo de revisar.

También aquí quité el multiplicador por 100 del front por las razones que le expliqué, solo me faltó quitar también la división por 100 del back, pero en la branch 49 si tomo en cuenta eso. Además, claro, de pasar el ordenamiento al back y añadir el campo de rank según ordenamiento.

Debido a todos esos cambios, la branch 49 es una versión actualizada de este código en la que se toma en cuenta:

- La nueva distribución de la función sortArray y uso de porcentaje de errores en vez de número de errores debido a que es más conveniente para el ranking.
- El retirar la multiplicación por 100 en el Front.
- Retirar división por 100 en el Back.
- Pasar método de ordenamiento sortArray al Back porque es el que da el ranking.
- Añadir campo de ranking al array final que es retornado por el Back mediante petición del Front.

**Comment by edwin-navarrete** [comment]
resuelto con otro issue
