### ISSUE TITLE
La UI de Stats debe enviar la fecha al servicio /ranking para que sea filtrado en el servidor

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#53]
Actualmente el código del UI está filtrando del lado del JS por fecha. Esa tarea debe hacerse del lado del servidor en el entrypoint de /ranking, ejemplo:

/ranking?started_on=2022-11-26

En la consulta se puede entonces:

WHERE DATE(FROM_UNIXTIME(a.started_on/1000)) = '2022-11-26'

**Comment by edwin-navarrete** [comment]
Estimado: 15 de Mayo

**Comment by jcalderonagudelo** [comment]
Se realiza pull request  en #57 listo para revisión.
