### ISSUE TITLE
Se necesitan la metadata de las preguntas en la BD 

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#54]
Usando la información que hay en client\src\features\game\data\es\questionDB.json y client\src\features\game\data\es\questionDB.json crear la tabla **question** en el script **db_schema\ssolucio_cyberalbum.sql**
con la siguiente estructura (escoga el dato más apropiado para cada caso):

id
type
lang
question
options
solution
difficulty
feedback
 
Incluir los inserts correspondientes:
INSERT INTO `question` VALUES 
(1, ... ) -- pregunta uno 
(2, ... ) -- pregunta dos ..

**Comment by KaremVPintoF** [comment]
Las preguntas siempre serán de opción múltiple y con cuatro posibles opciones, osea A B C o D?

**Comment by KaremVPintoF** [comment]
Siguiendo la organización original dada por el json de preguntas de prueba "sampleQuestions.json" se dejará de la siguiente manera:

CREATE TABLE ssolucio_cyberalbum.question (
id INT NOT NULL AUTO_INCREMENT,
type ENUM('OPEN', 'CLOSED') NOT NULL,
lang VARCHAR(45) NOT NULL,
question VARCHAR(255) NOT NULL,
option ENUM('A', 'B', 'C', 'D') NOT NULL,
solution ENUM('A', 'B', 'C', 'D') NOT NULL,
feedback VARCHAR(255) NOT NULL,
PRIMARY KEY (id));

**Comment by KaremVPintoF** [comment]
Sería así con los cambios de Whatsapp

CREATE TABLE `question` (
  `id` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `type` enum('SINGLE','MULTIPLE') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `lang` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `question` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  `options` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  `solution` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `feedback` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci DEFAULT NULL,
  `difficulty` float NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

**Comment by jcalderonagudelo** [comment]
Se ha realizado un PR a esta issue, por favor revisar @edwin-navarrete
