### ISSUE TITLE
Crear vista de desempeño de preguntas

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#56]
Con el entry point creado en el ticket https://github.com/edwin-navarrete/cybersec_album/issues/55 crear la vista correspondiente que consiste en:
Título: Desempeño de preguntas
Filtros: dos campos de fecha para especificar desde que fecha y hasta qué fecha regresar los datos. Cualquiera de los dos puede ser vacío.
Contenido:
Una tabla mostrando una columna por cada campo que retorna el entrypoint. La tabla puede ordenarse por latencia promedio y por probabilidad de éxito. 

Se llega a esta vista por el menú que está en la parte superior izquierda de la vista de stats.

**Comment by camartinezm92** [comment]
Se crea la vista de espuestas, se tieine una novedad el firlto de orden no logra identificar de forma adecuada los datos provenientes de avgLatency

**Comment by camartinezm92** [comment]
Se crean los cambios solicitados y se realiza actualizacion de la rama apra verificion y validacion.
