### ISSUE TITLE
La vista de Tabla de Clasificación no debe mostrar todos los resultados si hay una fecha seleccionada

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#72]
Actualmente la vista de estadísticas [https://albumstat.4ssoluciones.com/](https://albumstat.4ssoluciones.com/) retorna todos los resultados si no encuentra ningún resultado para la fecha actual. Este comportamiento es muy confuso para los usuario. Como debe funcionar es que si NO hay ninguna fecha seleccionada entonces muestre todos los resultados pero si el control muestra una fecha especifica debe retornar únicamente los resultados de esa fecha, sin importar si no hay resultados.

**Comment by camartinezm92** [comment]
Se crea nueva rama con la issue #72-La-vista-de-Tabla-de-Clasificación-no-debe-mostrar-todos-los-resultados-si-hay-una-fecha-seleccionada](https://github.com/edwin-navarrete/cybersec_album/tree/%2372-La-vista-de-Tabla-de-Clasificaci%C3%B3n-no-debe-mostrar-todos-los-resultados-si-hay-una-fecha-seleccionada, implementan indicaciones.

por favor revisar @edwin-navarrete gracias !
