### ISSUE TITLE
Se necesita un nuevo entrypoint /questions en el proyecto /server

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#74]
Con la información que está en la tabla `question` se necesita hacer un entrypoint 
GET \questions?lang=
donde lang puede ser "en" para inglés y "es" para español y debe generar exactamente la misma estructura (y contenido) json del archivo correspondiente al lenguaje:

\client\src\features\game\data\en\questionDB.json. 
\client\src\features\game\data\es\questionDB.json. 

El entrypoint tiene debe estar autenticado a través del header g-recaptcha-response, tal como se hace con los entrypoints tipo POST

../routes/questions.ts

**Comment by camartinezm92** [comment]
Creación nadae lang

**Comment by edwin-navarrete** [comment]
@camartinezm92 Por favor crea el PR.
Para modificar sólamente estos cambios en la salida JSON de modo que sea compatible con la estructura que ya existe en los archivos JSON de preguntas:

- "id" en vez de "questionId"
- "type" en vez de "questionType"
- eliminar del response "lang"
