### ISSUE TITLE
Actualizar preguntas del juego

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#79]
Según la hoja de cálculo que se encuentra en el ticket:
[https://github.com/edwin-navarrete/cybersec_album/issues/32](https://github.com/edwin-navarrete/cybersec_album/issues/32)

el objetivo es reemplazar el contenido de los archivos JSON localizados en:

cybersec_album\client\src\features\game\data\en\questionDB.json
cybersec_album\client\src\features\game\data\es\questionDB.json

Donde la carpeta "en" contiene la versión de las preguntas en inglés, la carpeta "es" contiene la versión en español. 

Una vez actualizados, verificar la visualización de todas las preguntas en el album en móviles (Chrome developer tools/ responsive view) y determinar el tamaño máximo del texto, en particular del feedback.

**Comment by SFAbril3** [comment]
Se actualizan las preguntas con las respectivas respuestas y feedback.

**Comment by edwin-navarrete** [comment]
It was rejected due to problems caused in the visualization. a new PR with fixes will be issued
