### ISSUE TITLE
Falla el ordenamiento de la tabla de clasificación

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#86]
https://albumstat.4ssoluciones.com/ El top jugador debe ser el más rápido y el que comente menos errores, por lo tanto hay que ordenar por 
- los que terminaron el album  (Primero los que sí terminaron)
- El numero de errores (Ascendente)
- El tiempo en que terminó el album (Ascendente)

**Comment by camartinezm92** [comment]
Se crea PR con la rama main
