### ISSUE TITLE
La tabla de clasificación debe mostrar el nombre del jugador

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/cybersec_album#88]
En caso de que el nombre esté nulo o vacío usar los último 4 caracteres del id del álbum

**Comment by camartinezm92** [comment]
Se crea PR sobre el cambio en la bd para la asignación de nombre al álbum y muestra de este dentro de la estadística del juego

**Comment by camartinezm92** [comment]
Se actualiza la bd de álbum con el nombre de jugador y se elimina de la db user_anserws.
